name: Tinybird – Sync all GCS datasources

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  

env:
  TINYBIRD_HOST: ${{ secrets.TINYBIRD_HOST }} 
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  fetch-list:
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.get.outputs.list }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Get datasource list
        id: get
        run: |
          set -eo pipefail
          resp=$(curl -sS -w "\n%{http_code}" \
            -H "Authorization: Bearer $TINYBIRD_TOKEN" \
            "$TINYBIRD_HOST/v0/pipes/list_ingest_targets.json")

          body=$(echo "$resp" | head -n -1)
          status=$(echo "$resp" | tail -n 1)

          if [ "$status" != "200" ]; then
            echo "::error::Tinybird API devolvió $status → $body"
            exit 1
          fi

          list=$(echo "$body" | jq -c '[.data[]?.datasource_name]')
          echo "list=$list"
          echo "list=$list" >> "$GITHUB_OUTPUT"

  sync:
    needs: fetch-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        datasource: ${{ fromJson(needs.fetch-list.outputs.list) }}
    steps:
      - name: Trigger ingestion
        run: |
          echo "Syncing ${{ matrix.datasource }}..."
          curl -sf -X POST \
            -H "Authorization: Bearer $TINYBIRD_TOKEN" \
            "$TINYBIRD_HOST/v0/datasources/${{ matrix.datasource }}/scheduling/runs"
