name: Tinybird - test - GCS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  
env:
  TINYBIRD_HOST: ${{ secrets.TINYBIRD_HOST }}
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: sync datasource
        run: |
          curl -X POST "https://api.tinybird.co/v0/datasources/raw_gcs_asmdcod/scheduling/runs" \
            -H "Authorization: Bearer p.eyJ1IjogImQ2YTJkMjM5LTViNWUtNDFmYy1iYzk1LTQwZDM2NDQyOGQ3MyIsICJpZCI6ICJhZTNhOGRhZi1hZjM0LTQ3Y2EtYjU2Ny0xNDM2OGU3NmQzYzMiLCAiaG9zdCI6ICJldV9zaGFyZWQifQ.TvtjY4OR4aQqRwEYSCEkvtKc9I1as54eV_bJuYxnGJI"
